# Node.js Express Web App to Linux on Azure
# Build a Node.js Express app and deploy it to Azure as a Linux web app.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: Ubuntu
      vmImage: kst-VirtualBox
    workspace:
      clean: all

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        cd old-api
        npm install
        cd ../web
        npm install
      displayName: 'npm install, build and test'
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
- stage: Test
  displayName: UI Testing Stage
  jobs:
  - job: ToscaTesting
    displayName: ToscaTest
    pool:
      name: Default
    workspace:
      clean: all
    steps:

    - task: CmdLine@2
      displayName: 'Run Tosca CI'
      inputs:
        script: '$(Agent.HomeDirectory)\\Client\\ToscaCIClient.exe -m distributed -c C:\\Users\\KST\\Documents\\agent\\Client\\CITestExecutionConfiguration.xml -t junit -r $(Common.TestResultsDirectory)\\ToscaCI.xml'
    - task: PublishTestResults@2
      inputs:
        testResultsFormat: JUnit
        testResultsFiles: '**/ToscaCI*.xml'
        searchFolder: '$(Common.TestResultsDirectory)'
        failTaskOnFailedTests: true
        testRunTitle: 'Publish ToscaCI Test Results'
        
